apiVersion: v1
kind: Service
metadata:
  name: mario-service
  namespace: thinkbotlabs
spec:
  selector:
    app: mario
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort